apiVersion: v2
name: crowd
description: A chart for installing Crowd Data Center on Kubernetes
type: application
version: 0.14.0
appVersion: 4.3.5-jdk11
kubeVersion: ">=1.19.x-0"
keywords:
  - Crowd
  - Crowd Server
  - Crowd Data Center
  - Crowd DC
  - Atlassian
home: https://www.atlassian.com/software/crowd
icon: https://atlassian-labs.github.io/data-center-helm-charts/icons/crowd.svg
sources:
  - https://github.com/atlassian-labs/data-center-helm-charts
  - https://bitbucket.org/atlassian-docker/docker-atlassian-crowd/
deprecated: false
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update Crowd version to 4.3.5-jdk11
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/212