{{- if .Values.confluence.localProxy.enable -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-local-proxy-config
  labels:
    {{- include "common.labels.commonLabels" . | nindent 4 }}
data:
  Caddyfile: |
    {{ .Values.ingress.host }}:{{ include "confluence.ingressPort" . }} {
    {{- if .Values.ingress.https }}
      tls /cert/cert.pem /cert/cert-key.pem
    {{- end }}

      reverse_proxy {{ .Values.synchrony.ingress.path | default "/synchrony" }}/* {{ include "synchrony.fullname" . }}:{{ .Values.synchrony.service.port }}
    }

    {{- with .Values.confluence.localProxy.additionalConfig }}
    {{ . | nindent 4 }}
    {{- end }}
{{- end -}}