apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.commonLabels" . | nindent 4 }}
  annotations:
    {{- with .Values.confluence.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.confluence.service.type }}
  ports:
    - port: {{ .Values.confluence.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.confluence.ports.hazelcast }}
      targetPort: hazelcast
      protocol: TCP
      name: hazelcast
  selector:
    {{- include "common.labels.selectorLabels" . | nindent 4 }}
