apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-jvm-config
  labels:
    {{- include "common.labels.commonLabels" . | nindent 4 }}
data:
  additional_jvm_args: >-
    {{- range .Values.bamboo.additionalJvmArgs }}
    {{ . }}
    {{- end }}
  max_heap: {{ .Values.bamboo.resources.jvm.maxHeap }}
  min_heap: {{ .Values.bamboo.resources.jvm.minHeap }}