apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
  {{- include "common.labels.commonLabels" . | nindent 4 }}
  annotations:
  {{- with .Values.bamboo.service.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.bamboo.service.type }}
  ports:
    - port: {{ .Values.bamboo.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- include "common.labels.selectorLabels" . | nindent 4 }}
